name = "ARITH2025"
author = "Jeffrey A. Sarnoff <jeffrey.sarnoff@ieee.org>"
uuid = "49b08ed8-2b77-46a8-b765-ceed15bdf9b3"
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
MiniFloatModels = "839dff2b-6fdf-4386-afa2-f3721eae4ce7"

[compat]
Combinatorics = "1"
MiniFloatModels = "0.1 - 0.5
julia = "1.11"
