name = "ARITH2025"
author = "Jeffrey A. Sarnoff <jeffrey.sarnoff@ieee.org>"
uuid = "49b08ed8-2b77-46a8-b765-ceed15bdf9b3"
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
Combinatorics = "1"
julia = "1.11"
