name = "ARITH2025"
author = "Jeffrey A. Sarnoff <jeffrey.sarnoff@ieee.org>"
uuid = "49b08ed8-2b77-46a8-b765-ceed15bdf9b3"
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MiniFloatModels = "839dff2b-6fdf-4386-afa2-f3721eae4ce7"

[compat]
Combinatorics = "1"
Plots = "2"
Makie = "0.21 - 0.50"
LaTeXStrings = "1.4"
MiniFloatModels = "0.1 - 0.5"
julia = "1.11"
